# Generated by Django 3.1.6 on 2021-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Дата публікації'),
        ),
    ]
