# Generated by Django 3.1.6 on 2021-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_auto_20210204_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я працівника")),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('photo', models.ImageField(upload_to='teammate_photos/', verbose_name='Фото працівника')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
    ]
