# Generated by Django 3.1.6 on 2021-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_teammate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery_photo/', verbose_name='Фото з галереї')),
            ],
            options={
                'verbose_name': 'Фотографія з галереї',
                'verbose_name_plural': 'Фотографії галереї',
            },
        ),
    ]
